In [ ]:
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np

img = cv.imread('C:/Users/KIIT/Downloads/baboon.jpg', 1)
print(type(img))
print(img)
print(img.shape)
px = img[100, 100]
print(px)

cv.imshow('Image', img)
cv.waitKey()
cv.destroyAllWindows()

<class 'numpy.ndarray'>
[[[  7  48  33]
  [  5  46  31]
  [  2  45  30]
  ...
  [ 92 129 133]
  [ 85 131 138]
  [ 86 138 144]]

 [[  8  49  34]
  [  5  48  33]
  [  3  46  31]
  ...
  [ 88 125 129]
  [ 80 126 133]
  [ 79 131 137]]

 [[  6  49  34]
  [  5  48  33]
  [  5  48  35]
  ...
  [ 88 125 129]
  [ 78 124 131]
  [ 76 128 134]]

 ...

 [[ 52  39  41]
  [ 57  44  46]
  [ 56  43  45]
  ...
  [  4   6   6]
  [  3   5   5]
  [  2   4   4]]

 [[ 53  40  42]
  [ 57  44  46]
  [ 56  43  45]
  ...
  [  2   4   4]
  [  1   3   3]
  [  0   2   2]]

 [[ 56  43  45]
  [ 58  45  47]
  [ 55  42  44]
  ...
  [  1   3   3]
  [  0   2   2]
  [  0   1   1]]]
(1343, 1000, 3)
[21 67 74]


In [ ]:
image=img.imread('baboon.jpg')
print(image.shape)

In [ ]:
cv.imshow('a',image)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
b,g,r=cv.split(img)
b=img[;,;,0]
g=img[;,;,1]
r=img[;,;,2]
print(r)
cv.imshow('Image',r)
cv.waitkey()
cv.destroyAllWindows()


In [ ]:
import cv2 as cv
import numpy as np

img = cv.imread('C:/Users/KIIT/Downloads/baboon.jpg')

height, width, channels = img.shape


inverted = np.zeros((height, width, channels), dtype=np.uint8)


for y in range(height):
    for x in range(width):
        for c in range(channels):
            inverted[y,x,c] = 255 - img[y,x,c]

cv.imshow('Inverted', inverted)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
b, g, r = cv.split(img)
g[:] = 0
result = cv.merge((b, g, r))
cv.imshow('Result', result)
cv.waitKey(0)
cv.destroyAllWindows()