In [4]:
import pandas as pd
Tables=pd.read_html("https://www.w3schools.com/html/html_tables.asp")
len(Tables)
Tables[1]

Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table

In [2]:
# Inverse of a 2D matrix 
import numpy as np


A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [8]:
#transpose of a matrix 
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


In [15]:
#Determinant of matrix

import numpy as np
n_array=np.array([[60,20],[30,44]])
print("Numpy Matrix is:")
print(n_array)
det=np.linalg.det(n_array)
print("\nDeterminant of matrix:")
print(int(det))

Numpy Matrix is:
[[60 20]
 [30 44]]

Determinant of matrix:
2039


In [17]:
#use functions bincount
import numpy as np
n=np.array([2,4,5,6,7,8])
print(np.bincount(n))

[0 0 1 0 1 1 1 1 1]


In [18]:
#use function flatten 
arr=np.array([[2,1],[3,5],[8,6]])
print(arr.flatten())

[2 1 3 5 8 6]


In [ ]:
#use function ravel


In [19]:
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np
ing=cv.imread("C:\Users\KIIT\Downloads\baboon.jpeg",1)
print(type(ing))
print(ing)
print(ing.shape)
px=ing[100,100]
print(px)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3152933815.py, line 4)